name: .NET Build

on:
  push:
    branches:
      - master
      - main
      - dev
      - develop
      - development
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ["10.0.x"]
        runtime-identifier: ["win-x64"]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore --runtime ${{ matrix.runtime-identifier }}
      - name: Build with dotnet
        run: dotnet build MediainfoProjectNg --configuration Release --no-restore --runtime ${{ matrix.runtime-identifier }}
      - name: Publish with dotnet
        run: dotnet publish MediainfoProjectNg --configuration Release --no-build --runtime ${{ matrix.runtime-identifier }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: "MediainfoProjectNg"
          path: |
            MediainfoProjectNg\bin\Release\net10.0-windows\win-x64\publish\MediainfoProjectNg.exe
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            MediainfoProjectNg\bin\Release\net10.0-windows\win-x64\publish\MediainfoProjectNg.exe
